server:
  port: 8083

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  redis:
    port: 6379
    host: 127.0.0.1

delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: false

greenpay:
  openapi:
    security:
      sign:
        enabled: true
        allow_types: md5,hmac_md5,rsa