server:
  port: 8083

logging:
  level:
    com.github.binarywang.wxpay: fatal
    me.chanjar.weixin: fatal
    com.esiran.greenpay.common.sign: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/greenpay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: greenpay
  redis:
    port: 6379
    host: redis
  resources:
    chain:
      strategy:
        content:
          enabled: true

greenpay:
  web:
    hostname: http://api.pay.leyyx.cn
  openapi:
    security:
      sign:
        enabled: true
        allow_types: rsa